import { Poppins } from 'next/font/google'
import './globals.css'
import Menubar from './homepage/page'

const poppins = Poppins({
  subsets: ['latin'],
  weight: '600'
})

export const metadata = {
  title: 'Invoice system',
  description: 'Generated by Invoice system',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="max-w-screen-xl mx-auto px-4 pt-4 md:px-8">
        {/* <ToastBar /> */}
        <Menubar />

        {children}
      </body>
    </html>
  )
}
